// <auto-generated />
using BioPark.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BioPark.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230306051711_Populando banco")]
    partial class Populandobanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("BioPark.Model.Apartamento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Disponibilidade")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("EdificioId")
                        .HasColumnType("int");

                    b.Property<string>("Locador")
                        .HasColumnType("text");

                    b.Property<string>("Locatario")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("ID");

                    b.HasIndex("EdificioId");

                    b.ToTable("Apartamentos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Disponibilidade = false,
                            EdificioId = 1,
                            Locador = "Bruno",
                            Locatario = "BioPark",
                            Numero = "25",
                            Valor = 560.0
                        },
                        new
                        {
                            ID = 2,
                            Disponibilidade = false,
                            EdificioId = 1,
                            Locador = "Felipe",
                            Locatario = "BioPark",
                            Numero = "55",
                            Valor = 600.0
                        },
                        new
                        {
                            ID = 3,
                            Disponibilidade = false,
                            EdificioId = 1,
                            Locador = "Luiza",
                            Locatario = "BioPark",
                            Numero = "84",
                            Valor = 700.0
                        },
                        new
                        {
                            ID = 4,
                            Disponibilidade = false,
                            EdificioId = 1,
                            Locador = "Gabriela",
                            Locatario = "BioPark",
                            Numero = "110",
                            Valor = 800.0
                        },
                        new
                        {
                            ID = 5,
                            Disponibilidade = false,
                            EdificioId = 1,
                            Locador = "Antonio",
                            Locatario = "BioPark",
                            Numero = "65",
                            Valor = 625.0
                        },
                        new
                        {
                            ID = 6,
                            Disponibilidade = true,
                            EdificioId = 1,
                            Locatario = "BioPark",
                            Numero = "56",
                            Valor = 600.0
                        },
                        new
                        {
                            ID = 7,
                            Disponibilidade = false,
                            EdificioId = 1,
                            Locador = "Marcelo",
                            Locatario = "BioPark",
                            Numero = "77",
                            Valor = 650.0
                        },
                        new
                        {
                            ID = 8,
                            Disponibilidade = true,
                            EdificioId = 1,
                            Locatario = "BioPark",
                            Numero = "12",
                            Valor = 400.0
                        },
                        new
                        {
                            ID = 9,
                            Disponibilidade = true,
                            EdificioId = 1,
                            Locatario = "BioPark",
                            Numero = "13",
                            Valor = 400.0
                        },
                        new
                        {
                            ID = 10,
                            Disponibilidade = true,
                            EdificioId = 2,
                            Locatario = "BioPark",
                            Numero = "10",
                            Valor = 900.0
                        },
                        new
                        {
                            ID = 11,
                            Disponibilidade = false,
                            EdificioId = 2,
                            Locador = "Bruna",
                            Locatario = "BioPark",
                            Numero = "11",
                            Valor = 560.0
                        },
                        new
                        {
                            ID = 12,
                            Disponibilidade = true,
                            EdificioId = 2,
                            Locatario = "BioPark",
                            Numero = "12",
                            Valor = 560.0
                        },
                        new
                        {
                            ID = 13,
                            Disponibilidade = false,
                            EdificioId = 2,
                            Locador = "Aurelio",
                            Locatario = "BioPark",
                            Numero = "13",
                            Valor = 905.0
                        },
                        new
                        {
                            ID = 14,
                            Disponibilidade = false,
                            EdificioId = 2,
                            Locador = "Maicon",
                            Locatario = "BioPark",
                            Numero = "14",
                            Valor = 999.0
                        },
                        new
                        {
                            ID = 15,
                            Disponibilidade = true,
                            EdificioId = 2,
                            Locatario = "BioPark",
                            Numero = "15",
                            Valor = 945.0
                        },
                        new
                        {
                            ID = 16,
                            Disponibilidade = false,
                            EdificioId = 2,
                            Locador = "Marcio",
                            Locatario = "BioPark",
                            Numero = "16",
                            Valor = 945.0
                        },
                        new
                        {
                            ID = 17,
                            Disponibilidade = false,
                            EdificioId = 2,
                            Locador = "Marcio",
                            Locatario = "BioPark",
                            Numero = "17",
                            Valor = 330.0
                        },
                        new
                        {
                            ID = 18,
                            Disponibilidade = true,
                            EdificioId = 2,
                            Locatario = "BioPark",
                            Numero = "18",
                            Valor = 901.0
                        });
                });

            modelBuilder.Entity("BioPark.Model.Edificio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ApartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Edificios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApartamentoId = 1,
                            Nome = "A"
                        },
                        new
                        {
                            Id = 2,
                            ApartamentoId = 3,
                            Nome = "B"
                        });
                });

            modelBuilder.Entity("BioPark.Model.Apartamento", b =>
                {
                    b.HasOne("BioPark.Model.Edificio", "Edificios")
                        .WithMany("Apartamentos")
                        .HasForeignKey("EdificioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edificios");
                });

            modelBuilder.Entity("BioPark.Model.Edificio", b =>
                {
                    b.Navigation("Apartamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
