// <auto-generated />
using BioPark.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BioPark.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230306043256_criando edificios")]
    partial class criandoedificios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("BioPark.Model.Apartamento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Disponibilidade")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("EdificioId")
                        .HasColumnType("int");

                    b.Property<string>("Locador")
                        .HasColumnType("text");

                    b.Property<string>("Locatario")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("ID");

                    b.HasIndex("EdificioId");

                    b.ToTable("Apartamentos");
                });

            modelBuilder.Entity("BioPark.Model.Edificio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ApartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Edificios");
                });

            modelBuilder.Entity("BioPark.Model.Apartamento", b =>
                {
                    b.HasOne("BioPark.Model.Edificio", "Edificios")
                        .WithMany("Apartamentos")
                        .HasForeignKey("EdificioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edificios");
                });

            modelBuilder.Entity("BioPark.Model.Edificio", b =>
                {
                    b.Navigation("Apartamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
